### ISSUE TITLE
Add metrics to API

### ISSUE THREAD

**Issue by mostafa** [gatewayd-io/gatewayd#187]
Part of #181.

**Comment by yakkshit** [comment]
Add prometheus metric to count the number of GetServers calls 



![Image](https://github.com/gatewayd-io/gatewayd/assets/63894727/2198f87b-83ea-4a3e-b3ab-6c1779a081ad)

**Comment by mostafa** [comment]
Hey @yakkshit,

I suppose you started working on this, so I assigned the ticket to you.
