### ISSUE TITLE
Create Helm chart for GatewayD

### ISSUE THREAD

**Issue by mostafa** [gatewayd-io/gatewayd#301]
https://github.com/gatewayd-io/k8s-experiments

**Comment by xirehat** [comment]
Dear @mostafa 

This link is not found! If you agree, create a project `helm-charts` like Grafana [helm-charts](https://github.com/grafana/helm-charts).
After that assign this task to me.

**Comment by mostafa** [comment]
Hey @xirehat,

thanks for offering to contribute. Now you can access the [k8s-experiments](https://github.com/gatewayd-io/k8s-experiments) repo. I also created the [helm-charts](https://github.com/gatewayd-io/helm-charts) repo. Please fork it and send PRs for review. 🙏
