### ISSUE TITLE
Graceful shutdown

### ISSUE THREAD

**Issue by mostafa** [gatewayd-io/gatewayd#439]
Add graceful shutdown to different parts of the system:

- [x] API: gRPC server
- [x] API: HTTP gateway
- [ ] more?

**Comment by zeina1i** [comment]
Hi @mostafa 

Can I take this task?

**Comment by mostafa** [comment]
Hey @zeina1i,

Of course! :pray:

**Comment by mostafa** [comment]
Hey @zeina1i,

Are there any updates?

**Comment by zeina1i** [comment]
Hey @mostafa 

Yes. I would push the code in one hour.

**Comment by zeina1i** [comment]
Hey @mostafa 
The PR is ready to be reviewed
https://github.com/gatewayd-io/gatewayd/pull/490
