### ISSUE TITLE
Replace go-capturer with logging to buffer

### ISSUE THREAD

**Issue by mostafa** [gatewayd-io/gatewayd#457]
Currently go-capturer wraps many test functions to capture their output. Sometimes we are initializing and passing the logger directly in the test function, so it would be easier to test writing logs to a buffer and then comparing the results with what we want. For examples, refer to [this test file](https://github.com/rs/zerolog/blob/master/log_test.go).

**Comment by Hamsajj** [comment]
Hello, I'd like to work on this issue. 

Can you help me to find which tests should be converted to use buffer instead?
The only tests that I find that are using capturer and can benefit from this change are in `hclog_adapter_test.go`.
Other tests are either testing a command ran directly with `executeCommandC` without passing a logger, or are testing the console output option of the log itself.

**Comment by mostafa** [comment]
Hey!

Assigned it to you. The `executeCommandC` function uses the `root.SetOut` function to use a bytes buffer instead of `os.Stdout` and it returns it as a string. Maybe we can use it as well, instead of go-capturer. Also, some usages of go-capturer are still valid, I suppose.
