### ISSUE TITLE
Add a way to cancel actions

### ISSUE THREAD

**Issue by mostafa** [gatewayd-io/gatewayd#463]
From `act/registry.go:253`:
> // TODO: Add a way to cancel the action.

This can be achieved using `context.WithTimeout` or something similar, just like policy evaluation timeout.

**Comment by Hamsajj** [comment]
Hello, I'd like to work on this if no one else is.

Do you want to add a timeout option to async actions and their config? or create a way to signal them somehow to be canceled?
