### ISSUE TITLE
Default Docker Compose Up Fails

### ISSUE THREAD

**Issue by sinadarbouy** [gatewayd-io/gatewayd#537]
## Description
I tried setting up GatewayD using Docker Compose, but ran into some issues in the docker-compose.yml file.

1. The `install_plugins` service in the `docker-compose.yml` relies on a `setup.sh` file. If the `GATEWAYD_VERSION` variable isn't set, it requires a `git` command to function properly in the first command(The installation of git now occurs later in that file). Otherwise, it encounters errors such as:
```
2024-05-21 22:29:21 /setup.sh: line 10: git: not found
2024-05-21 22:29:22   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
2024-05-21 22:29:22                                  Dload  Upload   Total   Spent    Left  Speed
100     9  100     9    0     0     30      0 --:--:-- --:--:-- --:--:--    30
2024-05-21 22:29:22 tar: invalid magic
2024-05-21 22:29:22 tar: short read
```
2. Also, the `setup.sh` script only knows how to install the GatewayD version for `AMD64` computers. But I'm using `ARM64`, so it's a no-go. It'd be nice if the script could figure out what kind of computer I'm on and download the right stuff.

3. When the `install_plugin`s service doesn't work, Docker just draws info and says it's "Exited." It'd be way cooler if it could tell me it failed.
Container `gatewayd-install_plugins-1`  Exited  but it `failed`
```
╰─ docker-compose up -d
[+] Running 4/5
⠼ Network gatewayd_default              Created                                                                                                                                                   6.5s
✔ Container gatewayd-postgres-1         Healthy                                                                                                                                                   6.3s
✔ Container gatewayd-install_plugins-1  Exited                                                                                                                                                    0.8s
✔ Container gatewayd-redis-1            Healthy                                                                                                                                                   5.8s
✔ Container gatewayd-gatewayd-1         Started

╰─ gatewayd-install_plugins-1 container log:
2024-05-21 22:29:21 /setup.sh: line 10: git: not found
```

## Expected Behavior

The `install_plugins` service in `docker-compose.yaml` file should successfully install the necessary components without errors.

## Current Behavior

The `install_plugins` service fails with the aforementioned errors

## Steps to Reproduce

1. Clone the repository and navigate to the directory containing the docker-compose.yml file.
2. Execute docker-compose up -d (without setting `GATEWAYD_VERSION` )

## Context

- Operating System and architecture:  Darwin - arm64
- GatewayD version: latest (v0.9.5)
- Plugins' versions: gatewayd-plugin-cache latest (v0.3.6)
- Other relevant information: all default configurations without changing any parameters

**Comment by mostafa** [comment]
Hey @sinadarbouy,

Thanks for testing and spotting the issues. 🙏 I am opening a PR soon to address the issues.
